### ISSUE TITLE
Sharing iP code quality feedback [for @autumn-sonata]

### ISSUE THREAD

**Issue by nus-se-script** [autumn-sonata/ip#6]
@autumn-sonata We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/commands/Command.java` lines `24-29`](https://github.com/autumn-sonata/ip/blob/8a12281b029c06e615313e7739fb8a8b4654eba3/src/main/java/commands/Command.java#L24..L29):

```java

    /**
     * Add a task to the task list.
     * @param task Specifies the task to be added to the task list.
     * @param tasks TaskList containing all the tasks currently available.
     * @param ui Specifies how the program interacts with the user.
     */

```

Example from [`src/main/java/commands/Command.java` lines `38-42`](https://github.com/autumn-sonata/ip/blob/8a12281b029c06e615313e7739fb8a8b4654eba3/src/main/java/commands/Command.java#L38..L42):

```java

    /**
     * Save the task list into the local txt file.
     * @param storage Stores and retrieves data from a local .txt file.
     * @param tasks TaskList containing all the tasks currently available.
     */

```

Example from [`src/main/java/drivers/Parser.java` lines `32-41`](https://github.com/autumn-sonata/ip/blob/8a12281b029c06e615313e7739fb8a8b4654eba3/src/main/java/drivers/Parser.java#L32..L41):

```java

    /**
     * Parse the command and calls the correct classes
     * to give the appropriate output.
     * @param fullCommand Full command given by the user.
     * @param ui Specifies how the program interacts with the user.
     * @return The command class to be executed.
     * @throws TumuException Parent exception for the program.
     * @throws NumberFormatException Exception is thrown when the String cannot be parsed
     *                               into an integer.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by autumn-sonata** [comment]
Fix issues related to phrasing of the overview statement in latest commit: e960661e344d182a0b4ade261d48157c9427b5bb
